baseURL: 'https://ghincea.eu/'
title: Marius Ghincea
languageCode: en-us

module:
  imports:
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind

pagination:
  pagerSize: 10

outputs:
  home:
    - HTML
    - RSS
    - headers

cascade:
  - _target:
      path: /publication/**
    pager: true
    editable: false
    show_related: true
    show_breadcrumb: true
    header:
      navbar:
        enable: true
