main:
  - name: Home
    url: /
    weight: 10
  - name: Research
    url: /research/
    weight: 20
  - name: Publications
    url: /publication/
    weight: 30
  - name: Teaching
    url: /teaching/
    weight: 40
  - name: Media
    url: /media/
    weight: 50
  - name: Blog
    url: /post/
    weight: 60
  - name: CV
    url: /uploads/cv.pdf
    weight: 70
