# Site parameters
marketing:
  analytics:
    google_analytics: ''
    google_tag_manager: ''

appearance:
  theme_day: minimal
  theme_night: minimal
  font: native
  font_size: L

header:
  navbar:
    enable: true
    blox: navbar
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true
    logo:
      text: "MG"

footer:
  copyright:
    notice: 'Â© {year} Marius Ghincea. All rights reserved.'

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

features:
  math:
    enable: false

seo:
  site_type: Person
  local_business_type: ''
  org_name: 'ETH Zurich'
  description: 'Marius Ghincea - Political Scientist at ETH Zurich. Research on great power competition and European integration.'
  twitter: 'MariusGhincea'
