[build]
  command = "npm install && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.155.2"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "22"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"
